name: Daily Stock CSV to Google Drive

on:
  schedule:
    - cron: '30 08 * * 1-5' # 평일 오후 5시 30분 (한국시간)
  workflow_dispatch: # 수동 실행 버튼

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

- name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 3.9에서 3.10으로 변경

      - name: Install Libraries
        run: |
          pip install --upgrade finance-datareader pandas pydrive2 oauth2client # --upgrade 추가

- name: Run Script
        env:
          GDRIVE_SERVICE_ACCOUNT_KEY: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        # 아래 부분을 수정합니다
        run: python update_stock_automatic.py
